# Generated by Django 3.2 on 2022-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_rename_ingredient_cake_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='weight'),
        ),
    ]
